<!DOCTYPE html>
<html lang="sv">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aboreto&family=Big+Shoulders+Stencil+Display:wght@100&family=Montserrat:ital,wght@0,400;1,300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a101703e57.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <title>Kontakt</title>
</head>
<body class="primary-bg">
    <div class="sub">
        <div class="sub-left">
            <img class="mobile-image" src="images/400PngdpiLogo.png" alt="logotype">
            <ul class="nav-list">
                <li>
                    <h3><a class="nav-link" href="index.php">HEM</a></h3>
                </li>
                <li>
                    <h3><a class="nav-link" href="kompetens.php">KOMPETENS</a></h3>
                </li>
                <li>
                    <h3><a class="nav-link" href="erfarenhet.php">ERFARENHET</a></h3>
                </li>
                <li>
                    <h3><a class="nav-link" href="extra.php">DET LILLA EXTRA</a></h3>
                </li>
                <li>
                    <h3><a class="nav-link" href="kontakt.php">KONTAKT</a></h3>
                </li>
                <li>
                    <img class="desktop-image" src="images/400PngdpiLogo.png" alt="logotype">
                </li>
            </ul>
        </div>
        <div class="sub-right contrasting-style">
            <h4>Anna Isoz</h4>
            <p>Eliselundsvägen 2</p>
            <p>277 30 Kivik</p>
            <p>072-403 01 85</p>
            <script type="text/javascript">/* Generated by www.email-encoder.com */
                for(var gegpuq=["YQ","Zg","bw","bw","YQ","aw","Ig","bw","bw","bQ","Lg","QA","aQ","Lw","bA","Yw","dQ","YQ","bA","Yw","Ig","QA","Pg","bQ","bQ","YQ","bg","bg","IA","bw","cw","aA","bQ","dQ","eg","bg","Yw","Lg","PQ","PA","bw","cw","Ig","YQ","YQ","bA","aw","bA","bg","Lg","cw","bw","bw","cw","IA","ZQ","bA","aQ","Pg","cg","eg","Lg","Og","dA","Ig","PQ","bw","PA","dA","bw","YQ","YQ","aQ","dA","bw","YQ","aQ"],zqduar=[55,6,71,31,10,32,37,26,67,46,56,25,21,74,49,39,63,75,29,70,45,61,51,72,9,19,18,54,2,30,43,3,36,27,24,17,34,69,7,73,14,22,8,1,47,40,68,12,53,33,58,62,23,42,38,5,65,57,76,4,60,20,15,64,50,44,59,0,13,66,52,16,48,28,35,41,11],bzbtpb=new Array,i=0;i<zqduar.length;i++)bzbtpb[zqduar[i]]=gegpuq[i];for(var i=0;i<bzbtpb.length;i++)document.write(atob(bzbtpb[i]+"=="));
                // --></script><noscript>Please enable JavaScript to see the email address (<a href="https://www.email-encoder.com/enablejs/" target="_blank" rel="noopener noreferrer">How-to</a>).</noscript>
        </div>
    </div>
    <?php include ("footer.php"); ?>
    <script src="script.js"></script>
</body>
</html>